"""delete preset related tables

Revision ID: 21738444686e
Revises: 6a7d22b6cc67
Create Date: 2025-10-30 21:19:05.231401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21738444686e'
down_revision: Union[str, Sequence[str], None] = '6a7d22b6cc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preset_pomodoros_id'), table_name='preset_pomodoros')
    op.drop_table('preset_pomodoros')
    op.drop_index(op.f('ix_preset_pomodoro_sessions_id'), table_name='preset_pomodoro_sessions')
    op.drop_table('preset_pomodoro_sessions')
    op.drop_index(op.f('ix_preset_sessions_id'), table_name='preset_sessions')
    op.drop_table('preset_sessions')
    op.drop_constraint(op.f('session_logs_preset_session_id_fkey'), 'session_logs', type_='foreignkey')
    op.drop_column('session_logs', 'preset_session_id')
    op.drop_constraint(op.f('user_pomodoro_logs_preset_pomodoro_id_fkey'), 'user_pomodoro_logs', type_='foreignkey')
    op.drop_column('user_pomodoro_logs', 'preset_pomodoro_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pomodoro_logs', sa.Column('preset_pomodoro_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_pomodoro_logs_preset_pomodoro_id_fkey'), 'user_pomodoro_logs', 'preset_pomodoros', ['preset_pomodoro_id'], ['id'])
    op.add_column('session_logs', sa.Column('preset_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('session_logs_preset_session_id_fkey'), 'session_logs', 'preset_sessions', ['preset_session_id'], ['id'])
    op.create_table('preset_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('preset_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['session_types.id'], name='preset_sessions_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preset_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_preset_sessions_id'), 'preset_sessions', ['id'], unique=False)
    op.create_table('preset_pomodoro_sessions',
    sa.Column('preset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['preset_pomodoros.id'], name=op.f('preset_pomodoro_sessions_preset_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['preset_sessions.id'], name=op.f('preset_pomodoro_sessions_session_id_fkey'))
    )
    op.create_index(op.f('ix_preset_pomodoro_sessions_id'), 'preset_pomodoro_sessions', ['id'], unique=False)
    op.create_table('preset_pomodoros',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('preset_pomodoros_pkey'))
    )
    op.create_index(op.f('ix_preset_pomodoros_id'), 'preset_pomodoros', ['id'], unique=False)
    # ### end Alembic commands ###
