"""add association table

Revision ID: 31175fe7c80a
Revises: 17da7b6c360d
Create Date: 2025-10-14 18:45:07.756629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31175fe7c80a'
down_revision: Union[str, Sequence[str], None] = '17da7b6c360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_session_association',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['preset_pomodoros.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['preset_sessions.id'], ),
    sa.PrimaryKeyConstraint('preset_id', 'session_id')
    )
    op.drop_constraint(op.f('preset_sessions_preset_id_fkey'), 'preset_sessions', type_='foreignkey')
    op.drop_column('preset_sessions', 'order')
    op.drop_column('preset_sessions', 'preset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset_sessions', sa.Column('preset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preset_sessions', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('preset_sessions_preset_id_fkey'), 'preset_sessions', 'preset_pomodoros', ['preset_id'], ['id'])
    op.drop_table('preset_session_association')
    # ### end Alembic commands ###
