"""add association table

Revision ID: 50879f927453
Revises: 8055e10e8a74
Create Date: 2025-10-30 20:01:46.768532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50879f927453'
down_revision: Union[str, Sequence[str], None] = '8055e10e8a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('preset_session_id', sa.Integer(), nullable=True))
    op.add_column('session_logs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('session_logs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.alter_column('session_logs', 'log_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'session_logs', 'preset_sessions', ['preset_session_id'], ['id'])
    op.add_column('user_pomodoro_logs', sa.Column('preset_pomodoro_id', sa.Integer(), nullable=True))
    op.add_column('user_pomodoro_logs', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('user_pomodoro_logs', sa.Column('rating', sa.Integer(), nullable=True))
    op.alter_column('user_pomodoro_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'user_pomodoro_logs', 'preset_pomodoros', ['preset_pomodoro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pomodoro_logs', type_='foreignkey')
    op.alter_column('user_pomodoro_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_pomodoro_logs', 'rating')
    op.drop_column('user_pomodoro_logs', 'comment')
    op.drop_column('user_pomodoro_logs', 'preset_pomodoro_id')
    op.drop_constraint(None, 'session_logs', type_='foreignkey')
    op.alter_column('session_logs', 'log_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('session_logs', 'finished_at')
    op.drop_column('session_logs', 'started_at')
    op.drop_column('session_logs', 'preset_session_id')
    # ### end Alembic commands ###
