"""add nullable false option

Revision ID: 610ba2e43526
Revises: ea375bbb1edf
Create Date: 2025-11-04 15:57:15.767313
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '610ba2e43526'
down_revision: Union[str, Sequence[str], None] = 'ea375bbb1edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ Enum 타입 먼저 생성
    sessionstatus_enum = sa.Enum('NOT_STARTED', 'ABORTED', 'COMPLETED', name='sessionstatus')
    sessionstatus_enum.create(op.get_bind())

    # 새 테이블 생성 (문제 없음)
    op.create_table(
        'user_stats',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('total_pomodoros', sa.Integer(), nullable=True),
        sa.Column('total_sessions', sa.Integer(), nullable=True),
        sa.Column('total_focus_duration', sa.Integer(), nullable=True),
        sa.Column('average_focus_rate', sa.Integer(), nullable=True),
        sa.Column('last_active_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('user_id')
    )

    # ✅ Step 1. nullable=True로 먼저 추가
    op.add_column('session_logs', sa.Column('status', sessionstatus_enum, nullable=True))

    # ✅ Step 2. 기존 row에 기본값 채우기 (여기선 NOT_STARTED로)
    op.execute("UPDATE session_logs SET status = 'NOT_STARTED' WHERE status IS NULL;")

    # ✅ Step 3. 이제 NOT NULL로 변경
    op.alter_column('session_logs', 'status', nullable=False)

    # ✅ 다른 컬럼들도 마찬가지로 nullable=True로 먼저 추가 가능
    op.add_column('session_logs', sa.Column('planned_duration', sa.Integer(), nullable=True))
    op.add_column('session_logs', sa.Column('actual_duration', sa.Integer(), nullable=True))
    op.add_column('session_logs', sa.Column('effective_duration', sa.Integer(), nullable=True))
    op.add_column('session_logs', sa.Column('missed_duration', sa.Integer(), nullable=True))

    # 기본값 채워넣기 (원하는 값이 있으면 조정 가능)
    op.execute("UPDATE session_logs SET planned_duration = 0 WHERE planned_duration IS NULL;")
    op.execute("UPDATE session_logs SET actual_duration = 0 WHERE actual_duration IS NULL;")
    op.execute("UPDATE session_logs SET effective_duration = 0 WHERE effective_duration IS NULL;")
    op.execute("UPDATE session_logs SET missed_duration = 0 WHERE missed_duration IS NULL;")

    # ✅ 마지막으로 모두 NOT NULL로 변경
    op.alter_column('session_logs', 'planned_duration', nullable=False)
    op.alter_column('session_logs', 'actual_duration', nullable=False)
    op.alter_column('session_logs', 'effective_duration', nullable=False)
    op.alter_column('session_logs', 'missed_duration', nullable=False)

    # 나머지는 그대로
    op.alter_column('session_logs', 'total_paused_duration', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('session_logs', 'duration')
    op.drop_column('session_logs', 'pause_count')

    # user_pomodoro_logs 도 동일하게 처리
    op.add_column('user_pomodoro_logs', sa.Column('total_effective_duration', sa.Integer(), nullable=True))
    op.add_column('user_pomodoro_logs', sa.Column('status', sessionstatus_enum, nullable=True))

    op.execute("UPDATE user_pomodoro_logs SET total_effective_duration = 0 WHERE total_effective_duration IS NULL;")
    op.execute("UPDATE user_pomodoro_logs SET status = 'NOT_STARTED' WHERE status IS NULL;")

    op.alter_column('user_pomodoro_logs', 'total_effective_duration', nullable=False)
    op.alter_column('user_pomodoro_logs', 'status', nullable=False)

    op.drop_column('user_pomodoro_logs', 'total_duration')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pomodoro_logs', sa.Column('total_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_pomodoro_logs', 'status')
    op.drop_column('user_pomodoro_logs', 'total_effective_duration')
    op.add_column('session_logs', sa.Column('pause_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('session_logs', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('session_logs', 'total_paused_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('session_logs', 'missed_duration')
    op.drop_column('session_logs', 'effective_duration')
    op.drop_column('session_logs', 'actual_duration')
    op.drop_column('session_logs', 'planned_duration')
    op.drop_column('session_logs', 'status')
    op.drop_table('user_stats')

    # ✅ Enum 타입 제거 (downgrade 시)
    sa.Enum(name='sessionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
