"""add association table

Revision ID: 6a7d22b6cc67
Revises: 9583eb764a55
Create Date: 2025-10-30 20:38:16.112616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7d22b6cc67'
down_revision: Union[str, Sequence[str], None] = '9583eb764a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('pause_count', sa.Integer(), nullable=True))
    op.add_column('session_logs', sa.Column('total_paused_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_logs', 'total_paused_duration')
    op.drop_column('session_logs', 'pause_count')
    # ### end Alembic commands ###
