"""add id key to pomodoro session table

Revision ID: 790ef0b60ed3
Revises: cdf2eb3bb263
Create Date: 2025-10-14 19:56:55.987600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790ef0b60ed3'
down_revision: Union[str, Sequence[str], None] = 'cdf2eb3bb263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. 기존 PK 제약 삭제
    op.drop_constraint(
        "preset_pomodoro_sessions_pkey",
        "preset_pomodoro_sessions",
        type_="primary"
    )

    # 2. id 컬럼 추가 및 PK 지정
    op.add_column(
        "preset_pomodoro_sessions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True)
    )

    # 3. (선택) preset_id와 session_id 인덱스 추가해두면 조회 빠름
    op.create_index("ix_preset_pomodoro_sessions_preset_id", "preset_pomodoro_sessions", ["preset_id"])
    op.create_index("ix_preset_pomodoro_sessions_session_id", "preset_pomodoro_sessions", ["session_id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preset_pomodoro_sessions_id'), table_name='preset_pomodoro_sessions')
    op.alter_column('preset_pomodoro_sessions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('preset_pomodoro_sessions', 'preset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('preset_pomodoro_sessions', 'id')
    # ### end Alembic commands ###
