"""add association table

Revision ID: 8055e10e8a74
Revises: be300997e9b1
Create Date: 2025-10-28 18:20:20.415769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8055e10e8a74'
down_revision: Union[str, Sequence[str], None] = 'be300997e9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset_sessions', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('preset_sessions', 'title')
    op.add_column('sessions', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'name')
    op.add_column('preset_sessions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('preset_sessions', 'name')
    # ### end Alembic commands ###
