"""add association table

Revision ID: be300997e9b1
Revises: 790ef0b60ed3
Create Date: 2025-10-28 18:07:49.170068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be300997e9b1'
down_revision: Union[str, Sequence[str], None] = '790ef0b60ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preset_pomodoro_sessions', 'preset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('preset_pomodoro_sessions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_preset_pomodoro_sessions_preset_id'), table_name='preset_pomodoro_sessions')
    op.drop_index(op.f('ix_preset_pomodoro_sessions_session_id'), table_name='preset_pomodoro_sessions')
    op.create_index(op.f('ix_preset_pomodoro_sessions_id'), 'preset_pomodoro_sessions', ['id'], unique=False)
    op.add_column('preset_sessions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'title')
    op.drop_column('preset_sessions', 'title')
    op.drop_index(op.f('ix_preset_pomodoro_sessions_id'), table_name='preset_pomodoro_sessions')
    op.create_index(op.f('ix_preset_pomodoro_sessions_session_id'), 'preset_pomodoro_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_preset_pomodoro_sessions_preset_id'), 'preset_pomodoro_sessions', ['preset_id'], unique=False)
    op.alter_column('preset_pomodoro_sessions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('preset_pomodoro_sessions', 'preset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
