"""Alter Table Schemas

Revision ID: cdf2eb3bb263
Revises: 31175fe7c80a
Create Date: 2025-10-14 19:32:04.987922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf2eb3bb263'
down_revision: Union[str, Sequence[str], None] = '31175fe7c80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_pomodoro_sessions',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['preset_pomodoros.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['preset_sessions.id'], ),
    sa.PrimaryKeyConstraint('preset_id', 'session_id')
    )
    op.drop_table('preset_session_association')
    op.drop_column('preset_pomodoros', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset_pomodoros', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('preset_session_association',
    sa.Column('preset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['preset_pomodoros.id'], name=op.f('preset_session_association_preset_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['preset_sessions.id'], name=op.f('preset_session_association_session_id_fkey')),
    sa.PrimaryKeyConstraint('preset_id', 'session_id', name=op.f('preset_session_association_pkey'))
    )
    op.drop_table('preset_pomodoro_sessions')
    # ### end Alembic commands ###
