"""add is_deleted column to Pomodoro table

Revision ID: d5137798e470
Revises: 610ba2e43526
Create Date: 2025-11-04 17:30:33.120172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5137798e470'
down_revision: Union[str, Sequence[str], None] = '610ba2e43526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pomodoros', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE pomodoros SET is_deleted = FALSE')  # 기존 행은 삭제되지 않은 걸로 초기화
    op.alter_column('pomodoros', 'is_deleted', nullable=False)  # 이제 not-null 적용
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoros', 'is_deleted')
    # ### end Alembic commands ###
