"""delete unnecessary tables

Revision ID: e190e8cfec25
Revises: 21738444686e
Create Date: 2025-10-31 14:48:33.019455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e190e8cfec25'
down_revision: Union[str, Sequence[str], None] = '21738444686e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_logs', 'preset_session_id')
    op.drop_column('user_pomodoro_logs', 'preset_pomodoro_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pomodoro_logs', sa.Column('preset_pomodoro_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('session_logs', sa.Column('preset_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
