"""add nullable false option

Revision ID: ea375bbb1edf
Revises: b80b390528da
Create Date: 2025-10-31 16:58:17.152993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea375bbb1edf'
down_revision: Union[str, Sequence[str], None] = 'b80b390528da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_logs', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_pomodoro_logs', 'pomodoro_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_pomodoro_logs', 'pomodoro_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('session_logs', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
